### ISSUE TITLE
Slippy link broken

### ISSUE THREAD

**Issue by qdread** [SESYNC-ci/leaflet-in-R-lesson#10]
the link to the definition of "slippy" maps is broken (https://www.planet.com/docs/guides/slippy-maps/) in very first paragraph. @khondula Do you have a good alternative off the top of your head?

**Comment by khondula** [comment]
Hm, looks like maybe it moved here? https://developers.planet.com/tutorials/slippy-maps-101/ but some of the images seem broken. 

I think the description on OSM might be a little too technical? https://wiki.openstreetmap.org/wiki/Slippy_Map

The images on here might work https://www.axismaps.com/guide/what-is-a-web-map

Not a super important part of the lesson... but the underlying way tile servers work could be interesting to some!

**Comment by qdread** [comment]
Replaced it with the osm link. Thanks Kelly!
