### ISSUE TITLE
add in some eval=TRUE chunks to show output

### ISSUE THREAD

**Issue by khondula** [SESYNC-ci/leaflet-in-R-lesson#2]

**Comment by khondula** [comment]
Getting an error instead of output: 

`Error in loadNamespace(name): there is no package called 'webshot'`

**Comment by itcarroll** [comment]
Transferring convo from email :)

I think it's worth trying to figure out how to get fancier stuff (i.e. live leaflet) into the jekyll pipeine. We certainly don't want a screenshot. 👎

The reason we don't currently output from Rmd to html (jekyll can just as easily serve html) is so we can wrap content in our custom <head>, to load consistent stylesheets, custom js, etc. Two possible solutions are 1) force Rmd to only export <body> or post-hoc strip off <head> or 2) make Rmd include the additional CSS, js we need in the <head> it creates. If 1 is possible I think that might lead to fewer breakages in the future. No doubt, however, there is <head> content that leaflet will need...

**Comment by itcarroll** [comment]
With a 'test.Rmd' file like

``````
---
output:
  html_document:
    keep_md: TRUE
    self_contained: FALSE
---

An empty `leaflet()` map.

```r
library(leaflet)

leaflet() %>%
    addTiles()
```
``````

then calling `render('test.Rmd')` gives you a "temporary" markdown with the HTML for the widget. I think we can hack this.

**Comment by itcarroll** [comment]
@khondula How does the lesson look with live leaflet?

**Comment by khondula** [comment]
!!! you are a magician, it's amazing!!  
looks like we could use some messages = FALSE params on chunks that read in spatial data

**Comment by khondula** [comment]
@itcarroll for the shiny parts, would it be worth it to put (more) demos on the shiny server, like the MODIS one from the blog post?

**Comment by itcarroll** [comment]
Yeah, I think demos would be great. Could you also put the code in a simple, clean public repo. Either on GitHub or gitlab. I know the code is in the lesson, but would be good to have an example of a clean project that has the whole file structure for data, etc.
