### ISSUE TITLE
add nlcd wms

### ISSUE THREAD

**Issue by khondula** [SESYNC-ci/leaflet-in-R-lesson#3]
perhaps a way to investigate custom leaflet CRS, since projection seems to be different than OSM

```
lc <- "https://smallscale.nationalmap.gov/arcgis/services/LandCover/MapServer/WMSServer"

leaflet() %>% 
  addTiles() %>%
  setView(lng = -76.505206, lat = 38.9767231, zoom = 12) %>%
  addWMSTiles(lc, layers = "1", 
              options = WMSTileOptions(format = "image/png", transparent = TRUE))
```

**Comment by khondula** [comment]
seems to be in correct projection now. Could still be useful to incorporate into lesson.

**Comment by andGarc** [comment]
A link with more information on defining custom CRS's was added.
Users can access this link and gain more information on the subject.
